import type { Metadata } from "next";
import { latoRegular, latoBold, interRegular, interBold } from "./font";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${latoRegular.variable} ${latoBold.variable} ${interRegular .variable} ${interBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
